// src/demos/GuestSpotDemo.vue
<template>
  <div class="p-2">
    <div class="relative w-full h-full max-w-screen-xl mx-auto flex flex-col gap-2 justify-center">
      <div class="relative w-full grow flex gap-4 overflow-hidden rounded-xl">
        <div v-if="mainPublisher" :key="mainPublisher.id" class="video-container flex size-full justify-center overflow-hidden">
          <ParticipantVideo :video-stream="mainPublisherVideoStream" class="host-video w-full h-full bg-surfaceAlt3" />
          <ParticipantAudio :audio-stream="mainPublisherAudioStream" />
        </div>
        <div v-else class="bg-surfaceAlt3 w-full h-full flex items-center justify-center text-uiText overflow-hidden">
          <VideoStatic />
        </div>
        <div class="absolute bottom-0 left-2 right-2 h-[50%] gradient-mask-t-80 flex items-end justify-normal">
          <ChatMessages ref="messages" class="pb-4" />
        </div>
      </div>
      <div :class="['absolute top-4 right-4 w-28 sm:w-36 aspect-[9/16] rounded-2xl overflow-hidden shadow-xl shadow-black/50 transform origin-top-right transition', {
        'scale-75': !guestPublisherVideoStream,
        'scale-100': guestPublisherVideoStream,
      }]">
        <div class="w-full h-full bg-black rounded-2xl flex items-center justify-center">
          <ParticipantVideo v-if="inGuestSpot" :video-stream="localPublisherVideoStream" :is-local="true" class="w-full h-full object-cover rounded-2xl" />
          <ParticipantVideo v-else-if="guestPublisherVideoStream" :video-stream="guestPublisherVideoStream" class="w-full h-full object-cover rounded-2xl" />
          <button v-if="!inGuestSpot" @click="handleSpotSelect" class="absolute flex flex-col gap-1 w-full h-full text-white items-center justify-center">
            <span class="absolute bottom-2 inset-x-2 rounded-xl inline-flex items-center justify-center bg-secondary text-white backdrop-blur-sm px-2 py-1.5">
              <span class="inline-flex gap-x-1 items-center drop-shadow-md">
                Replace
              </span>
              <span class="absolute inset-0 ring-2 ring-white/30 rounded-xl mix-blend-screen"></span>
            </span>
          </button>
        </div>
      </div>
      <DemoFooter :username="usernameStore.username" :replace-input="inGuestSpot">
        <LeaveButton @click="leaveGuestSlot" />
      </DemoFooter>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import { useUsernameStore } from '../stores/usernameStore'
import { usePopoverStore } from '../stores/popover';
import { useStageStore } from '../stores/stage';
import { fetchDemoToken } from '../utils/stage';
import ParticipantVideo from '../components/ParticipantVideo.vue';
import { StageEvents, StreamType } from 'amazon-ivs-web-broadcast';
import ParticipantAudio from '../components/ParticipantAudio.vue';
import DemoFooter from '../components/DemoFooter.vue';
import LeaveButton from '../components/LeaveButton.vue';
import ChatMessages from '../components/ChatMessages.vue';
import VideoStatic from '../components/VideoStatic.vue';

const usernameStore = useUsernameStore();
const popoverStore = usePopoverStore();
const stageStore = useStageStore();

const inGuestSpot = ref(false);
const localPublisherVideoStream = ref(null);
const localPublisherAudioStream = ref(null);

const mainPublisher = ref(null);
const mainPublisherVideoStream = ref(null);
const mainPublisherAudioStream = ref(null);

const guestPublisher = ref(null);
const guestPublisherVideoStream = ref(null);
const guestPublisherAudioStream = ref(null);

const isMainPublisher = (participant) => {
  return participant.userId === 'dealer-0';
}

const isGuestPublisher = (participant) => {
  return participant.userId === 'dealer-1';
}

const releaseLocalVideo = () => {
  const tracks = localPublisherVideoStream.value.getTracks();
  tracks.forEach((track) => {
    track.stop();
  });
  localPublisherVideoStream.value = null;
}

const handleSpotSelect = () => {
  popoverStore.getUserPermission(joinGuestSlot);
}

const joinGuestSlot = async () => {
  const videoStream = await navigator.mediaDevices.getUserMedia({ video: true, facingMode: 'user' });
  localPublisherVideoStream.value = videoStream;
  localPublisherAudioStream.value = null;
  inGuestSpot.value = true;
}

const leaveGuestSlot = () => {
  if (!localPublisherVideoStream.value) return;
  releaseLocalVideo();
  localPublisherAudioStream.value = null;
  inGuestSpot.value = false;
}

onMounted(async () => {
  if (!stageStore.stage) {
    const token = await fetchDemoToken(usernameStore.username, 'GUEST');
    await stageStore.connectToStage(token);
  }

  stageStore.stage.on(StageEvents.STAGE_PARTICIPANT_STREAMS_REMOVED, (participant) => {
    if (isMainPublisher(participant)) {
      mainPublisher.value = null;
      mainPublisherAudioStream.value = null;
      mainPublisherVideoStream.value = null;
    } else if (isGuestPublisher(participant)) {
      guestPublisher.value = null;
      guestPublisherAudioStream.value = null;
      guestPublisherVideoStream.value = null;
    }
  });

  stageStore.stage.on(StageEvents.STAGE_PARTICIPANT_STREAMS_ADDED, (participant, streams) => {
    if (isMainPublisher(participant)) {
      mainPublisher.value = participant;
      streams.forEach(stream => {
        if (stream.streamType === StreamType.AUDIO) {
          mainPublisherAudioStream.value = new MediaStream([stream.mediaStreamTrack]);;
        } else if (stream.streamType === StreamType.VIDEO) {
          mainPublisherVideoStream.value = new MediaStream([stream.mediaStreamTrack]);;
        }
      });
    } else if (isGuestPublisher(participant)) {
      guestPublisher.value = participant;
      streams.forEach(stream => {
        if (stream.streamType === StreamType.AUDIO) {
          guestPublisherAudioStream.value = new MediaStream([stream.mediaStreamTrack]);;
        } else if (stream.streamType === StreamType.VIDEO) {
          guestPublisherVideoStream.value = new MediaStream([stream.mediaStreamTrack]);;
        }
      });
    }
  });
});

onUnmounted(() => {
  leaveGuestSlot();
  stageStore.leaveStage();
})
</script>

<style scoped>
.video-container {
  container: video-player / size;
}

.host-video {
  object-fit: cover;
}

@container video-player (aspect-ratio > 0.7) {
  .host-video {
    object-fit: contain;
  }
}
</style>

// src/demos/GuestSpotDemo.jsx
import React, { useState, useEffect } from 'react';
import { useUsernameStore } from '../stores/useUsernameStore.js';
import { useStageStore } from '../stores/useStageStore.js';
import { StageEvents, StreamType } from 'amazon-ivs-web-broadcast';
import ParticipantVideo from '../components/stage/ParticipantVideo.jsx';
import ParticipantAudio from '../components/stage/ParticipantAudio.jsx';
import VideoStatic from '../components/stage/VideoStatic.jsx';
import ChatMessages from '../components/ui/ChatMessages.jsx';
import ControlBar from '../components/ui/ControlBar.jsx';
import { UserSquare } from '@phosphor-icons/react';

export default function GuestSpotDemo() {
  const username = useUsernameStore((s) => s.username);
  const { stageJoined, getStage, connectToStage, leaveStage } = useStageStore();

  const [inGuestSpot, setInGuestSpot] = useState(false);
  const [localPublisherVideoStream, setLocalPublisherVideoStream] = useState(null);

  const [mainPublisher, setMainPublisher] = useState(null);
  const [mainPublisherVideoStream, setMainPublisherVideoStream] = useState(null);
  const [mainPublisherAudioStream, setMainPublisherAudioStream] = useState(null);

  const [guestPublisher, setGuestPublisher] = useState(null);
  const [guestPublisherVideoStream, setGuestPublisherVideoStream] = useState(null);
  const [guestPublisherAudioStream, setGuestPublisherAudioStream] = useState(null);

  const isMainPublisher = (participant) => participant.userId === 'dealer-0';
  const isGuestPublisher = (participant) => participant.userId === 'dealer-1';

  const releaseLocalVideo = () => {
    if (localPublisherVideoStream) {
      localPublisherVideoStream.getTracks().forEach((track) => track.stop());
      setLocalPublisherVideoStream(null);
    }
  };

  const joinGuestSlot = async () => {
    try {
      const videoStream = await navigator.mediaDevices.getUserMedia({ video: true, facingMode: 'user' });
      setLocalPublisherVideoStream(videoStream);
      setInGuestSpot(true);
    } catch (err) {
      console.error('Failed to access camera for guest spot:', err);
    }
  };

  const leaveGuestSlot = () => {
    releaseLocalVideo();
    setInGuestSpot(false);
  };

  useEffect(() => {
    const stage = getStage();
    if (!stage) return;

    const onParticipantStreamsRemoved = (participant) => {
      if (isMainPublisher(participant)) {
        setMainPublisher(null);
        setMainPublisherAudioStream(null);
        setMainPublisherVideoStream(null);
      } else if (isGuestPublisher(participant)) {
        setGuestPublisher(null);
        setGuestPublisherAudioStream(null);
        setGuestPublisherVideoStream(null);
      }
    };

    const onParticipantStreamsAdded = (participant, streams) => {
      if (isMainPublisher(participant)) {
        setMainPublisher(participant);
        streams.forEach((stream) => {
          if (stream.streamType === StreamType.AUDIO) {
            setMainPublisherAudioStream(new MediaStream([stream.mediaStreamTrack]));
          } else if (stream.streamType === StreamType.VIDEO) {
            setMainPublisherVideoStream(new MediaStream([stream.mediaStreamTrack]));
          }
        });
      } else if (isGuestPublisher(participant)) {
        setGuestPublisher(participant);
        streams.forEach((stream) => {
          if (stream.streamType === StreamType.AUDIO) {
            setGuestPublisherAudioStream(new MediaStream([stream.mediaStreamTrack]));
          } else if (stream.streamType === StreamType.VIDEO) {
            setGuestPublisherVideoStream(new MediaStream([stream.mediaStreamTrack]));
          }
        });
      }
    };

    stage.on(StageEvents.STAGE_PARTICIPANT_STREAMS_REMOVED, onParticipantStreamsRemoved);
    stage.on(StageEvents.STAGE_PARTICIPANT_STREAMS_ADDED, onParticipantStreamsAdded);

    return () => {
      stage.off(StageEvents.STAGE_PARTICIPANT_STREAMS_REMOVED, onParticipantStreamsRemoved);
      stage.off(StageEvents.STAGE_PARTICIPANT_STREAMS_ADDED, onParticipantStreamsAdded);
    };
  }, [getStage()]);

  useEffect(() => {
    return () => {
      releaseLocalVideo();
      leaveStage();
    };
  }, []);

  return (
    <div style={{ display: 'flex', height: '100%', overflow: 'hidden' }}>
      <div className="guest-demo" style={{ flex: 1, minWidth: 0, position: 'relative' }}>
        
        {/* Main Stage View */}
        <div style={{ flex: 1, width: '100%', position: 'relative', borderRadius: 12, overflow: 'hidden', background: '#000' }}>
          {mainPublisher ? (
            <div style={{ width: '100%', height: '100%' }}>
              <ParticipantVideo stream={mainPublisherVideoStream} isLocal={false} />
              {mainPublisherAudioStream && <ParticipantAudio stream={mainPublisherAudioStream} />}
            </div>
          ) : (
            <VideoStatic />
          )}

          {/* Overlay gradient */}
          <div style={{
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            height: '40%',
            background: 'linear-gradient(to top, rgba(0,0,0,0.8) 0%, transparent 100%)',
            pointerEvents: 'none',
          }} />

          {/* PiP View for Guest Speaker */}
          <div
            className="guest-pip"
            style={{
              position: 'absolute',
              top: 16,
              right: 16,
              width: 140,
              aspectRatio: '9/16',
              borderRadius: 12,
              overflow: 'hidden',
              boxShadow: 'var(--shadow-lg)',
              border: '2px solid var(--border)',
              background: '#000',
              zIndex: 10,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            {inGuestSpot ? (
              <ParticipantVideo stream={localPublisherVideoStream} isLocal={true} />
            ) : guestPublisherVideoStream ? (
              <div style={{ width: '100%', height: '100%' }}>
                <ParticipantVideo stream={guestPublisherVideoStream} isLocal={false} />
                {guestPublisherAudioStream && <ParticipantAudio stream={guestPublisherAudioStream} />}
              </div>
            ) : (
              <button
                onClick={joinGuestSlot}
                style={{
                  width: '100%',
                  height: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: 8,
                  background: 'rgba(255, 255, 255, 0.05)',
                  cursor: 'pointer',
                  border: 'none',
                }}
              >
                <UserSquare size={32} color="var(--text-secondary)" />
                <span style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--blue)' }}>Join Spot</span>
              </button>
            )}
          </div>
        </div>

        {/* Chat Component */}
        <div style={{ height: 160, width: '100%', overflow: 'hidden' }}>
          <ChatMessages demoMode={true} />
        </div>

        {/* Controls */}
        <ControlBar
          isJoined={inGuestSpot}
          micEnabled={true}
          camEnabled={true}
          showChat={false}
          onToggleMic={() => {}}
          onToggleCam={() => {}}
          onLeave={leaveGuestSlot}
          onJoin={joinGuestSlot}
          joinLabel="Join Guest Spot"
        />
      </div>
    </div>
  );
}
